---
name: deploy

on:
    push:
        branches:
            - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install, build, and upload
              uses: withastro/action@v1
              with:
                  node-version: 20
            - name: Install SSH key
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  cat <<EOT >> ~/.ssh/config
                  Host github.com
                  HostName github.com
                  IdentityFile ~/.ssh/id_rsa
                  EOT
                  git config --global user.email "actions@github.com"
                  git config --global user.name "gh-actions"

            - name: Deploy website
              run: |
                  npm run deploy
            
